# Generated by Django 3.2.5 on 2021-07-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
