# Generated by Django 3.2.5 on 2021-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_anulate_producto_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='Productos'),
            preserve_default=False,
        ),
    ]
