# Generated by Django 3.2.5 on 2021-07-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='/media/vicente/ARCHIVOS VICENTE/CURSO DJANGO/utilesescolaresdj/applications/static/img/default/default-prod.png', upload_to='Productos'),
        ),
    ]
