# Generated by Django 3.2.5 on 2021-07-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210721_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=10, verbose_name='precio venta'),
        ),
    ]
